name: WorldGuard
main: MihaiChirculete\WorldGuard\WorldGuard
api: [3.0.0, 4.0.0]
mcpe-protocol: 408
version: 1.1.8
author: MihaiChirculete
website: https://github.com/MihaiChirculete/WorldGuard
commands:
  worldguard:
    description: Opens up the User Interface of WorldGuard.
    aliases: ["wg"]
    default: op
  region:
    description: Create/Manage/Delete regions.
    aliases: ["rg"]
    default: op
softdepend: ["RedstoneCircuit"]
permissions:
  worldguard.ui:
    default: op
  worldguard.create:
    default: op
  worldguard.modify:
    default: op
  worldguard.delete:
    default: op
  worldguard.enter:
    default: op
  worldguard.leave:
    default: op
  worldguard.place:
    default: op
  worldguard.block-place:
    default: op
  worldguard.break:
    default: op
  worldguard.block-break:
    default: op
  worldguard.edit:
    default: op
  worldguard.eat:
    default: op
  worldguard.drop:
    default: op
  worldguard.deathdrop:
    default: op
  worldguard.usechest:
    default: op
  worldguard.usechestender:
    default: op
  worldguard.usetrappedchest:
    default: op
  worldguard.enchantingtable:
    default: op
  worldguard.usedoors:
    default: op
  worldguard.usegates:
    default: op
  worldguard.usetrapdoors:
    default: op
  worldguard.usefurnaces:
    default: op
  worldguard.useanvil:
    default: op
  worldguard.usecauldron:
    default: op
  worldguard.usebrewingstand:
    default: op
  worldguard.usebeacons:
    default: op
  worldguard.usepressureplate:
    default: op
  worldguard.useusebutton:
    default: op
  worldguard.bypass.gamemode:
    default: op
